[package]
name = "omsim-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayref = "0.3.7"
bitflags = "2.4.2"
enum-iterator = "2.1.0"
